### ISSUE TITLE
 height must be > 0

### ISSUE THREAD

**Issue by skaematik** [edmodo/cropper#131]
java.lang.IllegalArgumentException: height must be > 0
- 3 non-project frames
1
at android.graphics.Bitmap.checkWidthHeight (Bitmap.java:393)
2
at android.graphics.Bitmap.createBitmap (Bitmap.java:696)
3
at android.graphics.Bitmap.createBitmap (Bitmap.java:665)
4
at com.edmodo.cropper.CropImageView.getCroppedImage (CropImageView.java:293)
5
at com.unsw.berrycount.activities.CameraActivity$1.onClick (CameraActivity.java:64)
- 9 non-project frames
6
at android.view.View.performClick (View.java:5232)
7
at android.view.View$PerformClick.run (View.java:21258)
8
at android.os.Handler.handleCallback (Handler.java:739)
9
at android.os.Handler.dispatchMessage (Handler.java:95)
10
at android.os.Looper.loop (Looper.java:179)
11
at android.app.ActivityThread.main (ActivityThread.java:5650)
12
at java.lang.reflect.Method.invoke (Unknown source)
13
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:791)
14
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:681)

**Comment by thomasfischersm** [comment]
Your issue might be the same as mine: https://github.com/edmodo/cropper/issues/134

I got the same error for width.

Does your image fill the ImageView entirely? Or is there a extra space because of  scaleType="centerInside"?

**Comment by narendra-keda** [comment]
Change Get Cropped Image function with this.
 public Bitmap getCroppedImage() {
         final Drawable drawable = getDrawable();
        if (drawable == null || !(drawable instanceof BitmapDrawable)) {
            return null;
        }
        // Get image matrix values and place them in an array.
        final float[] matrixValues = new float[9];
        getImageMatrix().getValues(matrixValues);

        // Extract the scale and translation values. Note, we currently do not handle any other transformations (e.g. skew).
        final float scaleX = matrixValues[Matrix.MSCALE_X];
        final float scaleY = matrixValues[Matrix.MSCALE_Y];
        final float transX = matrixValues[Matrix.MTRANS_X];
        final float transY = matrixValues[Matrix.MTRANS_Y];
    
    // Ensure that the left and top edges are not outside of the ImageView bounds.
        final float bitmapLeft = (transX < 0) ? Math.abs(transX) : 0;
        final float bitmapTop = (transY < 0) ? Math.abs(transY) : 0;
    
    // Get the original bitmap object.
        final Bitmap originalBitmap = ((BitmapDrawable) drawable).getBitmap();
        final float cropXPercentage = mBitmapRect.width() * 100 / originalBitmap.getWidth();
        final float cropYPercentage = mBitmapRect.height() * 100 / originalBitmap.getHeight();
    
    // Calculate the top-left corner of the crop window relative to the ~original~ bitmap size.
        final float cropX = (bitmapLeft + Edge.LEFT.getCoordinate()) * 100 / cropXPercentage;
        final float cropY = (bitmapTop + Edge.TOP.getCoordinate()-mBitmapRect.top) * 100 / cropYPercentage;// scaleY;
    
    // Calculate the crop window size relative to the ~original~ bitmap size.
        // Make sure the right and bottom edges are not outside the ImageView bounds (this is just to address rounding discrepancies).
        final float cropWidth = Edge.getWidth() * 100 / cropXPercentage;
        final float cropHeight = Edge.getHeight() * 100 / cropYPercentage;
    
      // Crop the subset from the original Bitmap.
        return Bitmap.createBitmap(originalBitmap,
                (int) cropX,
                (int) cropY,
                (int) cropWidth,
                (int) cropHeight);
    }
